### ISSUE TITLE
1 Faux Remaining

### ISSUE THREAD

**Issue by jun6lee** [obsidianmd/obsidian-importer#295] opened 2024-08-30 06:21 UTC
I've been using this for html import for a lack of an ePub option.
I extract out the html and then import the folder containing the html / or the html files directly.

I've been doing this over many months and it works perfectly.

> The dialog however always suggests that 1 file is remaining (although it's done).

![CShot 2024-08-30 at 11 49 18@2x](https://github.com/user-attachments/assets/e60cd6dd-24cf-49f8-9fb2-9f9476813e26)

Very minor annoyance, but it makes me always double-check that a file import hasn't been missed.
It never has.

**Comment by tgrosinger** [comment] 2024-10-08 20:49
Would you be able to provide us with an example that you are importing that demonstrates this issue so we can better debug and resolve this issue? Thank you.

**Comment by jun6lee** [comment] 2024-10-16 05:21
Sure, see the below

[OEBPS.zip](https://github.com/user-attachments/files/17389533/OEBPS.zip)

Unzip, import as html: 
- 2 failures for jpg files that are indeed missing.
- 1 remaining??

**Comment by tgrosinger** [comment] 2024-10-16 20:55
Thank you, that was very helpful. The issue is fixed in 1.6.10.

**Closed by tgrosinger** 2024-10-16 20:55 UTC
