### ISSUE TITLE
[OneNote] Does not discover nested section groups

### ISSUE THREAD

**Issue by hakenr** [obsidianmd/obsidian-importer#130] opened 2023-10-13 23:21 UTC
OneNote:
![image](https://github.com/obsidianmd/obsidian-importer/assets/12828888/cc82f318-ecf6-45bf-a4c4-af5eacd7b9df)

Importer:
![image](https://github.com/obsidianmd/obsidian-importer/assets/12828888/55a9b0d2-34c5-465d-8dfb-168ab802dcda)

**Comment by kepano** [comment] 2023-11-15 20:52
Duplicate of #162

**Closed by kepano** 2023-11-15 20:52 UTC
