### ISSUE TITLE
Apple Notes import is manual and gets duplicated

### ISSUE THREAD

**Issue by doranmartinez** [obsidianmd/obsidian-importer#252] opened 2024-05-15 17:05 UTC
The files imported get duplicated after running more than once.
Also, this is a very manual process. There isn't an obvious sync configuration.

I could be doing something wrong, I am a new user to the tool.

**Comment by kepano** [comment] 2024-05-15 17:27
This is a duplicate of #142

**Closed as completed by kepano** 2024-05-15 17:27 UTC
Labels: duplicate
