### ISSUE TITLE
OneNote images are imported as base64

### ISSUE THREAD

**Issue by philllie** [obsidianmd/obsidian-importer#336] opened 2024-12-15 20:35 UTC
this importer encodes all images automatically to base64 - a code that is about 10 pages long for every image.
the bad bad bad thing: if you search for a term it fill find hundreds and thousands of fake search results (hit in the url-code of base64) and you can try to "hit" the few correct ones among all those fake ones.
also the search becomes a multifold slower than it usually is.

**Comment by tgrosinger** [comment] 2024-12-16 22:05
Hi @philllie,
We have not been able to reproduce this. In our tests images are downloaded as separate files and embedded into the notes. Can you please tell us more about how you embedded the images in OneNote?

**Comment by tgrosinger** [comment] 2024-12-16 22:33
Ah, managed to reproduce the issue. It looks like if you store a base64 image in OneNote, then when importing it will save the file to the attachments folder as expected, however it still uses the base64 content in the note instead of a link to the downloaded attachment.

**Comment by tgrosinger** [comment] 2024-12-16 23:44
On closer inspection I have noticed it's actually saving the file in the attachment folder as expected but it's just setting the embedded image link text to the base64 data. So I think we can just remove that link text if it's base64 data.

**Comment by tgrosinger** [comment] 2024-12-17 00:01
Hello,
This should be resolved in 1.6.15. Please update to the latest release and let us know if you're still running into this problem. Thanks!

**Closed by tgrosinger** 2024-12-17 00:01 UTC
Labels: onenote

**Comment by tgrosinger** [comment] 2024-12-17 21:34
Could you please open the console and let me know what errors are shown there? Here are some instructions on opening the console and viewing logs: https://help.obsidian.md/Help+and+support#Capture+console+logs

**Comment by philllie** [comment] 2024-12-18 18:53
hi
to screenshots of errors, that i saw most often.
i did some comparison with my previous imports. it looks like, that there are indeed some images now and then failing to import, but the number is about the same as earlier - so certainly independent of the base64 adjustments.

(i noticed another bigger issue while importing, will open another tread, hope that is ok)
![err2](https://github.com/user-attachments/assets/77428ede-0cd3-4b81-ac3b-d32554306f09)
![err1](https://github.com/user-attachments/assets/f4ebb3fb-bb58-4561-a194-c5b22b227364)

**Comment by philllie** [comment] 2024-12-23 18:11
btw: thanks for the (quick) fix. it made obsidian after an import usable from not-usable
