### ISSUE TITLE
Apple Notes importer not working

### ISSUE THREAD

**Issue by franknu** [obsidianmd/obsidian-importer#144] opened 2023-10-19 17:51 UTC
I was really looking forward to using the new Apple Notes import option in Importer. But unfortunately it's not working for me. When I follow the instructions and click _Open_ on the popup for "group.com.apple.notes", the importer creates all the folders that are present in my Apple Notes but after that doesn't do anything anymore. The progress bar with the statistics remains on all zeros, no matter how long I leave it running. I've tried it with Apple Notes running and closed, doesn't make a difference. My notes are not locked. Any idea how to troubleshoot?

**Comment by rtblair** [comment] 2023-10-19 18:04
I've encountered similar behavior. 

In my case, it creates one folder and a sub-folder, but no files within either. The importer progress counts all remain at `0`.

For me, Apple Notes contains 1200+ notes in ~50 folders. So, it's failing pretty quickly.

**Comment by kepano** [comment] 2023-10-19 18:17
@mirnovov

**Comment by kepano** [comment] 2023-10-19 18:18
@franknu @rtblair can you provide debug info? Go to the command palette and choose `Show debug info` then copy/paste that here

**Comment by rtblair** [comment] 2023-10-19 18:20
```
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:57 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8112 23.0.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v7.3.2
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 10
	Plugins enabled: 10
		1: Actions URI v1.3.1
		2: Advanced URI v1.38.1
		3: Calendar v1.5.10
		4: Convert url to preview (iframe) v0.5.0
		5: Dataview v0.5.61
		6: Importer v1.5.2
		7: Minimal Theme Settings v7.3.0
		8: Natural Language Dates v0.6.1
		9: Tag Wrangler v0.6.1
		10: Templater v1.16.4

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by franknu** [comment] 2023-10-19 18:21
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103 23.0.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Prism v3.4.1
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 22
	Plugins enabled: 22
		1: Better Word Count v0.10.0
		2: Calendar v1.5.10
		3: Citations v0.4.5
		4: Dataview v0.5.61
		5: Day Planner v0.12.1
		6: Kanban v1.5.3
		7: Pandoc Plugin v0.4.1
		8: Reading Time v1.1.1
		9: Readwise Official v2.0.1
		10: Recent Files v1.3.8
		11: Style Settings v1.0.7
		12: Minimal Theme Settings v7.3.0
		13: Hider v1.3.1
		14: QuickAdd v1.4.0
		15: Tag Wrangler v0.6.1
		16: Outliner v4.8.0
		17: Zotero Integration v3.0.11
		18: Excalidraw v1.9.24
		19: Importer v1.5.1
		20: Projects v1.16.5
		21: Shortcut Launcher v1.0.1
		22: Tasks v4.9.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

I'm on MacOS 14.0 (Sonoma).

**Comment by mirnovov** [comment] 2023-10-19 19:23
@franknu @rtblair Does it show any errors in the developer console? (This can be shown via View -> Show Developer Tools)

**Comment by franknu** [comment] 2023-10-19 19:33
I'm not sure where to look in the console. Does this help?

```
app.js:1 Uncaught (in promise) Error: File name cannot contain any of the following characters: \ / :
    at jy (app.js:1:696095)
    at t.checkPath (app.js:1:703345)
    at t.<anonymous> (app.js:1:706008)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at app.js:1:236048
    at new Promise (<anonymous>)
    at v (app.js:1:235793)
    at t.createFolder (app.js:1:705896)
    at hr.createFolders (plugin:obsidian-importer:62:2451)
    at hr.resolveFolder (plugin:obsidian-importer:86:411)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async hr.import (plugin:obsidian-importer:72:69)
    at async HTMLButtonElement.eval (plugin:obsidian-importer:200:9812)
```

**Comment by mirnovov** [comment] 2023-10-19 19:41
Yes! It appears that your folder name contains some characters that means it can’t be created. The plugin should take care of this so I’ll work on an update but in the meantime, I’d try removing \ / or : from your folders temporarily.

**Comment by franknu** [comment] 2023-10-19 19:51
Oddly enough my folder names don't contain any of those three characters. They did contain + and < and - and I removed those, but it still doesn't work. I get the same error in the console. Does the same restriction go for the individual notes? I can image I might have used / \ or : in one of the titles of the 459 notes I have. 

```
Uncaught (in promise) Error: File name cannot contain any of the following characters: \ / :
    at jy (app.js:1:696095)
    at t.checkPath (app.js:1:703345)
    at t.<anonymous> (app.js:1:706008)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at app.js:1:236048
    at new Promise (<anonymous>)
    at v (app.js:1:235793)
    at t.createFolder (app.js:1:705896)
    at hr.createFolders (plugin:obsidian-importer:62:2451)
```

**Comment by mirnovov** [comment] 2023-10-19 19:55
No, since it creates the folders first and then the files. Do your folders have any other sort of special characters in their name?

**Comment by franknu** [comment] 2023-10-19 20:11
These are the folders in Apple Notes and after the import in Obsidian. Not all folders are apparently imported. And in Obsidian two folders are added: Geïmporteerd and Geïmporteerd 1 (in Dutch; imported and imported 1 in English).

<img width="285" alt="Apple Notes 2" src="https://github.com/obsidianmd/obsidian-importer/assets/148485748/5658acf3-bc9e-497b-bec6-07bd97cdb5a8">
<img width="288" alt="Apple Notes 1" src="https://github.com/obsidianmd/obsidian-importer/assets/148485748/bf3a2733-7a6d-47eb-9e7c-65bd0d9f6c07">
<img width="198" alt="Obsidian 2" src="https://github.com/obsidianmd/obsidian-importer/assets/148485748/6388a65f-8b69-4ed2-af77-7936791cd04d">
<img width="290" alt="Obsidian 1" src="https://github.com/obsidianmd/obsidian-importer/assets/148485748/7419d892-02d8-4ae1-b99c-f2e5698535be">

**Comment by mirnovov** [comment] 2023-10-20 05:16
Not sure why one of folders is failing in particular. Anyway, I've made a change so and so it handles illegal characters in folder names better. And if it fails on a specific folder, it will now keep going, and put the notes inside it in the root folder,.

**Comment by franknu** [comment] 2023-10-20 05:26
Okay thanks, I'll give it a try. Is the updated plugin version 1.5.2?

**Comment by mirnovov** [comment] 2023-10-20 07:58
@franknu Its not been merged yet I’m afraid, it’ll be 1.5.3

**Comment by scarrillo** [comment] 2023-10-23 18:35
Thank you all for the amazing work on this plugin. 

Just confirming that this is a problem for both folder and file names. I have many folders and filenames that contain both colons and dates. For example, a folder named: 1:1 (For one on one meetings).

The Obsidian/Chrome debugger does report the error as mentioned above.

**Comment by mirnovov** [comment] 2023-10-24 09:20
@scarrillo files work for me - are you sure the error isn't being caused by just the folders?

**Closed** 2023-10-24 17:14 UTC
Labels: bug, apple notes

**Comment by kepano** [comment] 2023-10-24 17:33
This should now be fixed if you update to Importer 1.5.3

**Comment by franknu** [comment] 2023-10-24 18:36
It works now! Thanks 🥳

**Comment by scarrillo** [comment] 2023-10-25 00:56
Apologies for the late response. Confirmed fixed.

I was using an older version of Obsidian (1.4.14). Today I upgraded both Obsidian (1.4.16) and Importer (1.5.3) before testing.  Previously Importer stalled with no updates, today Importer finished with a clear log of issues that I was able to resolve by tweaking a few Apple Notes.

Note errors which were easily resolved:
- _"because unexpected end of file"_
- _"because cannot read properties of undefined (reading 'zhexdata')"_
- _"because incorrect header check"_

Thank you! ❤️

**Comment by mackinra** [comment] 2024-07-07 08:25
> * "because incorrect header check"

@scarrillo I'm running into many imported Apple Notes failing this check, but don't understand it. The note looks fine to me. How did you resolve them?

**Comment by scarrillo** [comment] 2024-07-09 06:45
> > * "because incorrect header check"
> 
> @scarrillo I'm running into many imported Apple Notes failing this check, but don't understand it. The note looks fine to me. How did you resolve them?

Unfortunately, I did not remember how I resolved this. Ironically, I had a note saved with this information: 

> "because unexpected end of file" - Removed a special character that even notes had trouble rendering.

Take a look at a few examples and check for special characters.
