### ISSUE TITLE
[OneNote] Attachment imports fail for duplicate file names

### ISSUE THREAD

**Issue by SSzretter** [obsidianmd/obsidian-importer#198] opened 2024-01-08 19:01 UTC
If the same filename exists with note(s) the attachments are failing 'because Error: File already exists'.  
It should probably rename the attachment (1, 2, 3, etc.) in a loop so those attachments are not lost during import.

**Comment by krizman** [comment] 2024-01-09 22:14
Probably a duplicate of #126. I also have the same issue where I can't import a single notebook from OneNote. Copy-pasting content is also a futile task since for example the checkboxes get copied over as inline base64 encoded images ☑️ 😅

**Comment by lniass** [comment] 2024-01-23 04:57
I stopped migrating to Obsidian because I had too many files considered as "existing" that I did not want to lose.

Hoping there is soon a solution.

**Comment by tgrosinger** [comment] 2024-03-28 16:38
This should be resolved in the latest release - [1.6.1](https://github.com/obsidianmd/obsidian-importer/releases/tag/1.6.1)

**Closed by tgrosinger** 2024-03-28 16:38 UTC
Labels: bug, onenote
