### ISSUE TITLE
Convert from downloaded notebook

### ISSUE THREAD

**Issue by ChrisJones79** [obsidianmd/obsidian-importer#274] opened 2024-07-01 21:47 UTC
I've cleared out my OneDrive and my online notebooks along with it. So now I have the folder hierarchy and notes but I'm running linux. I've tried re-uploading the folder but it isn't recognized as a notebook, just oneNote files. 

I can't find instructions anywhere on how I can get these notes imported. They all appear to be .one or .onetoc2 filetypes. 

Is there anything that can be done?

**Comment by kepano** [comment] 2024-07-01 22:50
Duplicate of #98

**Closed by kepano** 2024-07-01 22:50 UTC
