### ISSUE TITLE
OneNote account login error

### ISSUE THREAD

**Issue by EvgeniyYadryshnikov** [obsidianmd/obsidian-importer#314] opened 2024-10-21 15:37 UTC
Hello,
OneNote account login error.

![image](https://github.com/user-attachments/assets/37ea7f08-3e38-4064-865a-9693e88503c0)

Windows 11. Last version Obsidian and Importer

**Comment by kepano** [comment] 2024-11-04 14:27
This is a duplicate of #233

**Closed by kepano** 2024-11-04 14:27 UTC
